iirt_announcement:
    resource: "@IirtAnnouncementBundle/Resources/config/routing.yml"
    prefix:   /annonces

iirt_message:
    resource: "@IirtMessageBundle/Resources/config/routing.yml"
    prefix:   /

iirt_user:
    resource: "@IirtUserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation
